version: "3.6"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/:ro
      - mongoData:/data/db
    ports:
      - ${MONGO_PORT}:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

networks:
  default:
    name: mongo

volumes:
  mongoData:
    name: AdWebserverMongoDB
